[versions]
agp = "8.2.0-alpha09"
databinding-runtime = "8.1.2"
hilt-android = "2.44"
safeargs = "2.7.5"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
lifecycle-viewmodel-ktx = "2.6.2"
material = "1.10.0"
constraintlayout = "2.1.4"
paging-rxjava2 = "3.2.1"
retrofit = "2.9.0"
rxandroid = "2.1.1"

org-jetbrains-kotlin-android = "1.8.0"
[libraries]

androidx-databinding-runtime = { module = "androidx.databinding:databinding-runtime", version.ref = "databinding-runtime" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycle-viewmodel-ktx" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle-viewmodel-ktx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging-rxjava2" }
androidx-paging-rxjava2 = { module = "androidx.paging:paging-rxjava2", version.ref = "paging-rxjava2" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
hilt-android = { module = "com.google.dagger:hilt-android", version = "2.48.1" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-android" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "4.12.0" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava2:rxjava", version = "2.2.21" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
hiltPlugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }
safeargs = { id = "androidx.navigation.safeargs", version.ref = "safeargs" }

org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
org-jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "org-jetbrains-kotlin-android" }

[bundles]

